trigger:
  branches:
    include:
      - main
    exclude:
      - feature/*

variables:
  - group: 'acr-settings'  # Load variables from the variable group
  - name: imageTag
    value: $(Build.BuildId)  # Override if needed

stages:
- stage: Build
  displayName: 'Build and Push Docker Image to ACR'
  jobs:
  - job: BuildPush
    displayName: 'Build and Push Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        containerRegistry: '$(azureSubscription)'  # service connection
        repository: '$(containerRepository)/$(imageName)' # just use either imagename or containerRepository
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          $(imageTag)
- stage: Deploy
  dependsOn: Build
  displayName: 'deploy to AKS'
  jobs:
    - job: 
      displayName: deploy to AKS
      steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: '$(azureSubscription)' # sevice connection
            azureResourceGroup: 'dev-rg'
            kubernetesCluster: '$(AKS-cluster-name)'
            manifests: 'deployment.yml'
