trigger:
  branches:
    include:
      - main
    exclude:
      - feature

variables:
  #azureSubscription: 'My-Azure-Service-Connection'  # Azure RM service connection name
  #azureResourceGroup: '1-5cdbb78d-playground-sandbox'
  # aksClusterName: 'my-aks-cluster'
  #containerRegistry: 'mainwebappacr'
  #imageName: 'myapp'
  #imageTag: '$(Build.BuildId)'
  - group: 'Docker Hub authentication credentials' # this is the name of Variable Group

stages:
- stage: Build
  displayName: 'Build and Push Docker Image to Docker'
  jobs:
  - job: BuildPush
    displayName: 'Build and Push'
    pool:
      name: 'Default'
    steps:
   # - task: Docker@2
     # displayName: 'Login to ACR'
     # inputs:
      #  command: login
       # containerRegistry: 'myacr-service-connection' # Docker registry service connection

    #- task: Docker@2
     # displayName: 'Build Docker Image'
      #inputs:
       # command: build
        #Dockerfile: 'dockerfile'
        #tags: |
         # $(containerRegistry)/$(imageName):$(imageTag)

    - task: Docker@2
      displayName: Build and push an image to Docker Hub
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
