trigger:
  branches:
    include:
      - main
    exclude:
      - feature/*
pool:
 #name: 'pool-1'
  name: 'Default'
variables:
  - group: 'acr-settings'  # Load variables from the variable group
  - name: imageTag
    value: $(Build.BuildId)  # Override if needed

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
      
  
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(acr-registary)
          tags: |
            $(imagetag)

   # - task: Docker@2
    #  displayName: 'Build and Push Image to ACR'
     # inputs:
      ## repository: '$(containerRepository)/$(imageName)' # just use either imagename or containerRepository
        #command: 'buildAndPush'
      #  Dockerfile: '**/dockerfile'
       # tags: |
        #  $(imageTag)
- stage: Deploy
  dependsOn: Build
  displayName: 'deploy to AKS'
  jobs:
    - job: 
      displayName: deploy to AKS
      steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: '$(azureSubscription)' # sevice connection
            azureResourceGroup: 'dev-rg'
            kubernetesCluster: '$(AKS-cluster-name)'
            manifests: 'deployment.yml'
