# Namespace (optional - uncomment if needed)
apiVersion: v1
kind: Namespace
metadata:
  name: springbootapi-ns

---
# Optional: ACR Auth Secret — skip this if you're using managed identity with AKS
# If using 'kubectl create secret docker-registry acr-auth-secret', keep it
# Otherwise, you can remove this block entirely and imagePullSecrets below
# apiVersion: v1
# kind: Secret
# metadata:
#   name: acr-auth-secret
#   namespace: springbootapi-ns
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: <your-base64-encoded-dockerconfigjson>

---
#apiVersion: v1
#kind: Secret
#metadata:
 # name: db-secret
 # namespace: springbootapi-ns
#type: Opaque
#stringData:
 # username: kishore@servr-1
 # password: 16nf1a0101@.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapi-deployment
  namespace: springbootapi-ns
  labels:
    app: springbootapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapi
  template:
    metadata:
      labels:
        app: springbootapi
    spec:
      containers:
        - name: springbootapi-container
          image: $(containerRegistry)/$(containerRepository)/$(imageName):$(imageTag)  # ⬅️ Reference from pipeline
          ports:
            - containerPort: 8080
          #env:
           # - name: SPRING_DATASOURCE_URL
            #  value: jdbc:mysql://servr-1.mysql.database.azure.com:3306/user-db?useSSL=true&requireSSL=true&verifyServerCertificate=false
            #- name: SPRING_DATASOURCE_USERNAME
             ##  secretKeyRef:
               #   name: db-secret
                #  key: username
            ## valueFrom:
              #  secretKeyRef:
               #   name: db-secret
                #  key: password
      #imagePullSecrets:
       # - name: acr-auth-secret  # Optional: skip if using managed identity
      # Optional nodeSelector:
      # nodeSelector:
      #   agentpool: usernp

---
apiVersion: v1
kind: Service
metadata:
  name: springbootapi-service
  namespace: springbootapi-ns
spec:
  type: LoadBalancer
  selector:
    app: springbootapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
