#apiVersion: v1
#kind: Namespace
#metadata:
  #name: springbootapi-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-auth-secret
  namespace: springbootapi-ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzcHJpbmdib290YXBpYWNyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJzcHJpbmdib290YXBpYWNyIiwicGFzc3dvcmQiOiJnUE5xR3lhMXlQVXdKdCtvejNwVjNRS3VWUkhUelRQZnZVeXVkbWhpL2srQUNSQ2x1V
jBPIiwiZW1haWwiOiJraXNob3JlMzI3ODBAZ21haWwuY29tIiwiYXV0aCI6ImMzQnlhVzVuWW05dmRHRndhV0ZqY2pwblVFNXhSM2xoTVhsUVZYZEtkQ3R2ZWpOd1ZqTlJTM1ZXVWtoVWVsUlFablpWZVhWa2JXaHBMMnNyUVVOU1EyeD
FWakJQIn19fQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapi-deployment
  namespace: springbootapi-ns
  labels:
    app: springbootapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapi
  template:
    metadata:
      labels:
        app: springbootapi
    spec:
      nodeSelector:
        agentpool: usernp
      containers:
        - name: springbootapi-container
          image: springbootapiacr.azurecr.io/image:v1.0
          ports:
            - containerPort: 8080
           env:
           - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://servr-1.mysql.database.azure.com:3306/user-db?useSSL=true&requireSSL=true&verifyServerCertificate=false
           - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
           - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
      imagePullSecrets:
        - name: acr-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapi-service
  namespace: springbootapi-ns
spec:
  type: LoadBalancer
  selector:
    app: springbootapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
