#apiVersion: v1
#kind: Namespace
#metadata:
  #name: springbootapi-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-auth-secret
  namespace: springbootapi-ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzcHJpbmdib290YXBpYWNyLWRnY2Vja2d1Z3RhNGRuY2QuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6InNwcmluZ2Jvb3RhcGlhY3IiLCJwYXNzd29yZCI6InBhYUp6ZkVpZE4yRlJwSlhhRmVkRUl0MmZZak1sRXIrWjNRUk1OVlZDRStBQ1JDc3hPS0siLCJlbWFpbCI6Imtpc2hvcmUzMjc4MEBnbWFpbC5jb20iLCJhdXRoIjoiYzNCeWFXNW5ZbTl2ZEdGd2FXRmpjanB3WVdGS2VtWkZhV1JPTWtaU2NFcFlZVVpsWkVWSmRESm1XV3BOYkVWeUsxb3pVVkpOVGxaV1EwVXJRVU5TUTNONFQwdEwifX19
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapi-deployment
  namespace: springbootapi-ns
  labels:
    app: springbootapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapi
  template:
    metadata:
      labels:
        app: springbootapi
    spec:
      nodeSelector:
        agentpool: usernp
      containers:
        - name: springbootapi-container
          image: springbootapiacr-dgceckgugta4dncd.azurecr.io/springboot-image:V2.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapi-service
  namespace: springbootapi-ns
spec:
  type: LoadBalancer
  selector:
    app: springbootapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
